name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  code_coverage:
    name: Run Code Coverage
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - uses: Gr1N/setup-poetry@v8
          with:
            poetry-version: "1.4.0"
        - name: Install dependencies
          run: |
            poetry install
        - name: Run Code Coverage
          run: |
            poetry run coverage run -m pytest
            poetry run coverage xml
        - uses: paambaati/codeclimate-action@v3.2.0
          env:
            CC_TEST_REPORTER_ID: 60717467966d9543f67fc08b0305b721b9fdb4395d4ec129bd1f26c2895649a3
          with:
            coverageCommand: poetry run coverage xml